export const READY = 'READY';

export const LIST_ADDRESS_START = 'LIST_ADDRESS_START';
export const LIST_ADDRESS_SUCCESS = 'LIST_ADDRESS_SUCCESS';
export const LIST_ADDRESS_FAILURE = 'LIST_ADDRESS_FAILURE';

export const ADD_ADDRESS_START = 'ADD_ADDRESS_START';
export const ADD_ADDRESS_SUCCESS = 'ADD_ADDRESS_SUCCESS';
export const ADD_ADDRESS_FAILURE = 'ADD_ADDRESS_FAILURE';

export const DELETE_ADDRESS_START = 'DELETE_ADDRESS_START';
export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS';
export const DELETE_ADDRESS_FAILURE = 'DELETE_ADDRESS_FAILURE';

export const STATUSES = [
  'READY',
  'LIST_ADDRESS_START', 
  'LIST_ADDRESS_SUCCESS', 
  'LIST_ADDRESS_FAILURE',
  'ADD_ADDRESS_START', 
  'ADD_ADDRESS_SUCCESS', 
  'ADD_ADDRESS_FAILURE',
  'DELETE_ADDRESS_START', 
  'DELETE_ADDRESS_SUCCESS', 
  'DELETE_ADDRESS_FAILURE'
] as const;